from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Melexis', src, depend = ['MLX90393_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
