from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('Melexis', src, depend = ['PKG_USING_MELEXIS'], CPPPATH = CPPPATH)

Return('group')
